const http = require("http")
const {token} = require('./token.js')

/*
  Replace the user id with the one randomly generated by the demo application.
  You should be able to find it in the logs after starting the service, denoted as:
  '[DEBUG] : WATCHING FOR KEY p98s3'
*/

const randomUserId = 'p98se'

const options = {
  hostname: 'localhost',
  port: 9000,
  path: `/authentication/${randomUserId}`,
  method: 'POST',
  headers: { 'Content-Type': 'application/json' }
}

const req = http.request(options, res => {
  res.setEncoding('utf8')
  res.on('data', body => {
    console.log('Body: ' + body)
  })
})

req.write(JSON.stringify({token}))
req.end()
